============================= test session starts ==============================
platform darwin -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/Chris/Documents/UWLing/clmbrs/altk
collected 6 items / 2 errors

==================================== ERRORS ====================================
__________________ ERROR collecting src/tests/test_grammar.py __________________
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/Users/Chris/anaconda3/envs/altk/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/test_grammar.py:1: in <module>
    from ultk.language.grammar import Grammar, GrammaticalExpression, Rule
ultk/language/grammar.py:54: in <module>
    @dataclass(eq=True, frozen=True)
/Users/Chris/anaconda3/envs/altk/lib/python3.11/dataclasses.py:1220: in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
/Users/Chris/anaconda3/envs/altk/lib/python3.11/dataclasses.py:1027: in _process_class
    _init_fn(all_init_fields,
/Users/Chris/anaconda3/envs/altk/lib/python3.11/dataclasses.py:545: in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
E   TypeError: non-default argument 'rule_name' follows default argument
_________________ ERROR collecting src/tests/test_language.py __________________
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/Users/Chris/anaconda3/envs/altk/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
/Users/Chris/anaconda3/envs/altk/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/test_language.py:9: in <module>
    class TestLanguage:
tests/test_language.py:57: in TestLanguage
    lang = Language(expressions=[dog, cat, tree, shroom])
ultk/language/language.py:59: in __init__
    if len(set([e.meaning.universe for e in expressions])) != 1:
<string>:3: in __hash__
    ???
E   TypeError: unhashable type: 'list'
=========================== short test summary info ============================
ERROR tests/test_grammar.py - TypeError: non-default argument 'rule_name' fol...
ERROR tests/test_language.py - TypeError: unhashable type: 'list'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.53s ===============================
